# ASF-ui is a node.js project
language: node_js

# We can save bandwidth by limiting git clone to only last 10 commits
git:
  depth: 10

# We target latest lts version of node.js
node_js: lts/*

script:
  - |
    set -eu

    npm run-script deploy --no-progress

    set +u # This is needed to continue Travis build
matrix:
  # We can use fast finish, as we don't need to wait for allow_failures builds to mark build as success
  fast_finish: true
  include:
    # We're building ASF-ui with node.js on latest versions of all available OSes
    # We need to declare latest image ourselves until https://github.com/travis-ci/travis-ci/issues/8922 is dealt with
    # Ref: https://docs.travis-ci.com/user/reference/linux
    - os: linux
      dist: bionic
    # Ref: https://docs.travis-ci.com/user/reference/osx
    - os: osx
      osx_image: xcode11.6
    # Ref: https://docs.travis-ci.com/user/reference/windows
    - os: windows
