blank_issues_enabled: false
contact_links:
  - name: ğŸ’» ArchiSteamFarm issue, unrelated to ASF-ui
    url: https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose
    about: Please open an issue in ArchiSteamFarm repo
  - name: ğŸŒ Localization improvement
    url: https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Localization
    about: Please use our crowdin platform
  - name: ğŸ”“ Security issue
    url: https://github.com/JustArchiNET/ASF-ui/blob/main/.github/SECURITY.md
    about: Please follow our security policy
