name: ASF-ui-translations

on:
  schedule:
  - cron: '0 2 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.4
      with:
        submodules: recursive
        token: ${{ secrets.ARCHIBOT_GITHUB_TOKEN }}

    - name: Download latest translations from Crowdin
      uses: crowdin/github-action@1.3.3
      with:
        upload_sources: false
        download_translations: true
        skip_untranslated_strings: true
        push_translations: false
        crowdin_branch_name: main
        config: '.github/crowdin.yml'
        project_id: ${{ secrets.ASF_CROWDIN_PROJECT_ID }}
        token: ${{ secrets.ASF_CROWDIN_API_TOKEN }}

    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v4.0.0
      with:
        gpg-private-key: ${{ secrets.ARCHIBOT_GPG_PRIVATE_KEY }}
        git-user-signingkey: true
        git-commit-gpgsign: true

    - name: Commit the changes
      shell: sh
      run: |
        set -eu

        git add -A "src/i18n/locale"

        if ! git diff --cached --quiet; then
            git commit -m "Automatic translations update"
        fi

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.ARCHIBOT_GITHUB_TOKEN }}
        branch: ${{ github.ref }}
